version: '3.8'
services:
  go-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./app/views:/go-app/views
      - ./database.db:/go-app/database.db
    environment:
      - ENV=production
